// Code generated by MockGen. DO NOT EDIT.
// Source: internal/user/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/user/repository.go -destination=internal/user/mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
